# org.example.Application configuration
spring:
  application:
    name: crud
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: 123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true

# Embedded server configuration
server:
  servlet:
    context-path: /${spring.application.name}
  port: 8080

# Open API configuration
openapi:
  info:
    description: Basic CRUD with swagger UI docs
    enabled: true

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true