CREATE TABLE Elements (
	ID int PRIMARY KEY,
	NAME varchar(50),
	TYPE varchar (2)
);

INSERT INTO ELEMENTS (ID, NAME, TYPE) VALUES (1, 'Element 1', 'AA');
INSERT INTO ELEMENTS (ID, NAME, TYPE) VALUES (2, 'Element 2', 'CD');
INSERT INTO ELEMENTS (ID, NAME, TYPE) VALUES (3, 'Element 3', 'CH');
INSERT INTO ELEMENTS (ID, NAME, TYPE) VALUES (4, 'Element 4', 'ZJ');
INSERT INTO ELEMENTS (ID, NAME, TYPE) VALUES (5, 'Element 5', 'XT');